version: 2.1
jobs: 
    build: 
        docker:
            - image: 'circleci/node:10.16.3'
        working_directory: ~/code
        steps:
            - checkout
            - run: 
                name: Install dependencies
                command: yarn install
            - run:
                name: Run test
                command: yarn test
            - store_test_results:
                path: api/tests/outputs
